version: '3'

services:
  front_asset_desk:
    container_name: front_asset_desk
    image: assetdesk:latest
    build:
      context: .
      dockerfile: ./apps/webapp/Dockerfile
    restart: always
    ports:
      - 9017:3000