export const CONTRACT_ADDRESS = 'CCCXDB2N2SAIGXLMQJCKCAMZNEWY2NNIPKPR2OXIJ3GDK65URAYF5TOQ';
export const FAUCET_CONTRACT_ADDRESS = 'CAXBKTF7RQFG3IHIQ2JERWW6RPXFKGZHPMUXEH3RLOW5XAFEF4C7M6VH';

export const EIGHTEEN_EXPONENT = 18;

export const USDC_EXPONENT = 8;
