export const CONTRACT_ADDRESS = 'CBAKPWXF7XYRHKY4MV4WJZU277QXPTI7T5KR4EFSFZFQITDIJOG7Q6QH';
export const FAUCET_CONTRACT_ADDRESS = 'CBUXCJUU23EYQE5CSCXSMPVNHVQ35XD4W3IABJAKZJU23WBXWOEVWBIZ';

export const EIGHTEEN_EXPONENT = 18;

export const USDC_EXPONENT = 8;
