export enum ContractMethods {
  BALANCE = 'balance',
  GET_PRICE = 'GetPrice',
  GET_DEPOSIT = 'GetDeposit',
  GET_USER_DEPOSITED_USD = 'GetUserDepositedUsd',
  GET_USER_BORROWED_USD = 'GetUserBorrowedUsd',
  GET_AVAILABLE_TO_BORROW = 'GetAvailableToBorrow',
  GET_USER_COLLATERAL_USD = 'get_user_collateral_usd',
  GET_AVAILABLE_TO_REDEEM = 'GetAvailableToRedeem',
  DEPOSIT = 'Deposit',
  REDEEM = 'Redeem',
  BORROW = 'Borrow',
  GET_USER_BORROW_AMOUNT_WITH_INTEREST = 'GetUserBorrowAmountWithInterest',
  GET_LIQUIDITY_RATE = 'GetLiquidityRate',
  GET_INTEREST_RATE = 'GetInterestRate',
  GET_TOTAL_RESERVES_BY_TOKEN = 'GetTotalReservesByToken',
  GET_TVL = 'GetTVL',
  USER_DEPOSIT_AS_COLLATERAL = 'UserDepositAsCollateral',
  TOGGLE_COLLATERAL_SETTING = 'ToggleCollateralSetting',
  GET_AVAILABLE_LIQUIDITY_BY_TOKEN = 'GetAvailableLiquidityByToken',
}
